package com.example.dynamicforms.service;

import com.example.dynamicforms.entity.FormConfig;
import com.example.dynamicforms.entity.FormField;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

@Service
public class DynamicTableService {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    public long countTable(String tableName, Map<String, Object> filters) {
        validateIdentifier(tableName);
        StringBuilder sql = new StringBuilder("SELECT COUNT(*) FROM " + tableName);
        List<Object> params = new java.util.ArrayList<>();

        if (filters != null && !filters.isEmpty()) {
            sql.append(" WHERE ");
            List<String> conditions = new java.util.ArrayList<>();

            for (Map.Entry<String, Object> entry : filters.entrySet()) {
                validateIdentifier(entry.getKey());
                if (entry.getValue() != null && !entry.getValue().toString().isEmpty()) {
                    conditions.add(entry.getKey() + " LIKE ?");
                    params.add("%" + entry.getValue() + "%");
                }
            }

            if (!conditions.isEmpty()) {
                sql.append(String.join(" AND ", conditions));
            }
        }

        return jdbcTemplate.queryForObject(sql.toString(), Long.class, params.toArray());
    }

    public void createTable(FormConfig formConfig) {
        String tableName = formConfig.getTableName();
        validateIdentifier(tableName);
        List<FormField> fields = formConfig.getFields();

        // 1. Create table if it doesn't exist
        StringBuilder sql = new StringBuilder("CREATE TABLE IF NOT EXISTS " + tableName + " (");
        sql.append("id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        sql.append(")");
        jdbcTemplate.execute(sql.toString());

        // 2. Add or Update columns
        for (FormField field : fields) {
            validateIdentifier(field.getName());
            String columnDef = mapFieldToColumnDef(field);
            String dbType = mapTypeToDbType(field.getType());

            // Try to add column
            try {
                String addSql = "ALTER TABLE " + tableName + " ADD COLUMN " + columnDef;
                jdbcTemplate.execute(addSql);
            } catch (Exception e) {
                // Column likely exists, try to modify type
                // Note: H2 syntax for modifying column type
                String modifySql = "ALTER TABLE " + tableName + " ALTER COLUMN " + field.getName() + " " + dbType;
                try {
                    jdbcTemplate.execute(modifySql);
                } catch (Exception ex) {
                    System.err.println("Failed to modify column " + field.getName() + ": " + ex.getMessage());
                    // Continue, might be incompatible type change
                }
            }
        }
    }

    private String mapFieldToColumnDef(FormField field) {
        String dbType = mapTypeToDbType(field.getType());
        return field.getName() + " " + dbType;
    }

    private String mapTypeToDbType(String formType) {
        switch (formType) {
            case "NUMBER":
                return "DOUBLE";
            case "DATE":
                return "DATE";
            case "BOOLEAN":
                return "BOOLEAN";
            case "TEXTAREA":
                return "VARCHAR(1000)";
            case "EMAIL":
                return "VARCHAR(255)";
            case "TEXT":
            case "SELECT":
            default:
                return "VARCHAR(255)";
        }
    }

    public List<Map<String, Object>> getAllData(String tableName) {
        validateIdentifier(tableName);
        String sql = "SELECT * FROM " + tableName;
        return jdbcTemplate.queryForList(sql);
    }

    public List<Map<String, Object>> searchTable(String tableName, Map<String, Object> filters, int limit, int offset) {
        validateIdentifier(tableName);
        StringBuilder sql = new StringBuilder("SELECT * FROM " + tableName);
        List<Object> params = new java.util.ArrayList<>();

        if (filters != null && !filters.isEmpty()) {
            sql.append(" WHERE ");
            List<String> conditions = new java.util.ArrayList<>();

            for (Map.Entry<String, Object> entry : filters.entrySet()) {
                validateIdentifier(entry.getKey());
                if (entry.getValue() != null && !entry.getValue().toString().isEmpty()) {
                    conditions.add(entry.getKey() + " LIKE ?");
                    params.add("%" + entry.getValue() + "%");
                }
            }

            if (!conditions.isEmpty()) {
                sql.append(String.join(" AND ", conditions));
            }
        }

        sql.append(" LIMIT ? OFFSET ?");
        params.add(limit);
        params.add(offset);

        return jdbcTemplate.queryForList(sql.toString(), params.toArray());
    }

    public void insertData(String tableName, java.util.Map<String, Object> data) {
        if (data == null || data.isEmpty()) {
            return;
        }
        validateIdentifier(tableName);

        StringBuilder sql = new StringBuilder("INSERT INTO " + tableName + " (");
        StringBuilder values = new StringBuilder("VALUES (");

        java.util.List<Object> params = new java.util.ArrayList<>();

        int i = 0;
        for (java.util.Map.Entry<String, Object> entry : data.entrySet()) {
            validateIdentifier(entry.getKey());
            if (i > 0) {
                sql.append(", ");
                values.append(", ");
            }
            sql.append(entry.getKey());
            values.append("?");
            params.add(entry.getValue());
            i++;
        }

        sql.append(") ");
        values.append(")");

        sql.append(values);

        jdbcTemplate.update(sql.toString(), params.toArray());
    }

    public void dropTable(String tableName) {
        validateIdentifier(tableName);
        String sql = "DROP TABLE IF EXISTS " + tableName;
        jdbcTemplate.execute(sql);
    }

    private void validateIdentifier(String identifier) {
        if (identifier == null || !identifier.matches("^[a-zA-Z0-9_]+$")) {
            throw new IllegalArgumentException("Invalid identifier: " + identifier);
        }
    }
}
